force-app/main/default/objects/Contract/fields/Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Name__c</fullName>
    <formula>Opportunity__r.Account.Name + &apos;-&apos; +  Opportunity__r.SubClient_or_Manufacturer__r.Name + &apos;-&apos; +  Opportunity__r.Name + &apos;-&apos; +  TEXT( Opportunity__r.Audience_Type__c )</formula>
    <label>Campaign Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <formula>TEXT(MONTH( StartDate )) + &apos;/&apos; + TEXT(YEAR( StartDate )) + &apos; - &apos; +
TEXT(MONTH(  EndDate )) + &apos;/&apos; + TEXT(YEAR( EndDate ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Flight</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>IO</relationshipLabel>
    <relationshipName>IO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposal</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>IO</relationshipLabel>
    <relationshipName>IO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>IO Invoice</label>
    <nameField>
        <displayFormat>INV-{000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IO Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Client_Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Campaign_Name__c</fullName>
    <label>Client Campaign Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/IO__c.field-meta.xml
<CustomField>
    <fullName>IO__c</fullName>
    <label>IO</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>IO Invoices</relationshipLabel>
    <relationshipName>Contract_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Invoice</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposal</label>
    <referenceTo>Quote</referenceTo>
    <relationshipName>Invoice</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>IO Invoice Line Item</label>
    <nameField>
        <displayFormat>INVL-{000}</displayFormat>
        <label>Invoice Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IO Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Counts__c.field-meta.xml
<CustomField>
    <fullName>Counts__c</fullName>
    <label>Counts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/CPM__c.field-meta.xml
<CustomField>
    <fullName>CPM__c</fullName>
    <label>CPM</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Impression__c.field-meta.xml
<CustomField>
    <fullName>Impression__c</fullName>
    <formula>( Sales_Price__c  /  CPM__c )*1000</formula>
    <label>Impression</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/IO__c.field-meta.xml
<CustomField>
    <fullName>IO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IO</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>IO Invoice Line Items</relationshipLabel>
    <relationshipName>IO_Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Monthly_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Frequency__c</fullName>
    <label>Monthly Frequency</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <label>Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Name__c</fullName>
    <label>Campaign Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Segment_Name__c.field-meta.xml
<CustomField>
    <fullName>Segment_Name__c</fullName>
    <description>Segment Info</description>
    <label>Segment Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity_Segment__c/Opportunity_Segment__c.object-meta.xml
<CustomObject>
    <label>Opportunity Segment</label>
    <nameField>
        <displayFormat>OS-{000}</displayFormat>
        <label>Opportunity Segment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Segments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Segment__c/fields/IO_Invoice__c.field-meta.xml
<CustomField>
    <fullName>IO_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IO Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Opportunity Segments</relationshipLabel>
    <relationshipName>Opportunity_Segments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Segment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Segments</relationshipLabel>
    <relationshipName>Opportunity_Segments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Segment__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segment</label>
    <referenceTo>Segment__c</referenceTo>
    <relationshipLabel>Opportunity Segments</relationshipLabel>
    <relationshipName>Opportunity_Segments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Impression__c.field-meta.xml
<CustomField>
    <fullName>Impression__c</fullName>
    <formula>( UnitPrice  /  ListPrice ) * 1000</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Impression</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Monthly_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Frequency__c</fullName>
    <defaultValue>30</defaultValue>
    <label>Monthly Frequency</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal_Invoice__c/Proposal_Invoice__c.object-meta.xml
<CustomObject>
    <label>Proposal Invoice</label>
    <nameField>
        <displayFormat>PIN-{000}</displayFormat>
        <label>Proposal Inovice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposal Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal_Invoice__c/fields/Client_Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Campaign_Name__c</fullName>
    <label>Client Campaign Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proposal_Invoice__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <label>Proposal</label>
    <referenceTo>Quote</referenceTo>
    <relationshipName>Proposal_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Name__c</fullName>
    <formula>Opportunity.Account.Name + &apos;-&apos; + Opportunity.SubClient_or_Manufacturer__r.Name + &apos;-&apos; + Opportunity.Name + &apos;-&apos; + TEXT( Opportunity.Audience_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Campaign Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Client_Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Campaign_Name__c</fullName>
    <label>Client Campaign Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <formula>TEXT(MONTH(  DATEVALUE(Flight_Start_Date__c) )) + &apos;/&apos; +  TEXT(YEAR( DATEVALUE(Flight_Start_Date__c) )) + &apos; - &apos; +  
 TEXT(MONTH( DATEVALUE(Flight_End_Date__c ) )) + &apos;/&apos; + TEXT(YEAR( DATEVALUE(Flight_End_Date__c )))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Flight</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Counts__c.field-meta.xml
<CustomField>
    <fullName>Counts__c</fullName>
    <label>Counts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/CPM__c.field-meta.xml
<CustomField>
    <fullName>CPM__c</fullName>
    <label>CPM</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Impression__c.field-meta.xml
<CustomField>
    <fullName>Impression__c</fullName>
    <formula>( UnitPrice  /   CPM__c  ) * 1000</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Impression</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Monthly_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Frequency__c</fullName>
    <label>Monthly Frequency</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Proposal_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposal Invoice</label>
    <referenceTo>Proposal_Invoice__c</referenceTo>
    <relationshipLabel>Proposal Line Items</relationshipLabel>
    <relationshipName>Proposal_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Segment__c/Segment__c.object-meta.xml
<CustomObject>
    <label>Segment</label>
    <nameField>
        <label>Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ProposalIOInvoiceCls.cls
public with sharing class ProposalIOInvoiceCls {
    
    @AuraEnabled
    public static List<Proposal_Invoice__c> getQuoteInvoice( Id quoteId ){
        System.debug('quoteId'+quoteId);
        try {
            return [SELECT Id, End_Date__c, Start_Date__c, Proposal__r.Opportunity.Segment_Name__c, Proposal__r.Flight__c, Proposal__r.Campaign_Name__c, Client_Campaign_Name__c,
                    ( SELECT UnitPrice, Product2.name, Quantity, 
                    CPM__c, Impression__c, Monthly_Frequency__c, PricebookEntryId,
                    Proposal_Invoice__c FROM Proposal_Line_Items__r )
                    FROM Proposal_Invoice__c WHERE 
                    Proposal__c = :quoteId 
                   ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static List<Opportunity_Segment__c> getOppSegments( Id quoteId, String objName ){
        if( objName == 'Contract' ){
            Contract q = [SELECT Opportunity__c FROM Contract WHERE Id = :quoteId];
            return  [SELECT Segment__r.Name, Segment__c, Start_Date__c, End_Date__c FROM Opportunity_Segment__c WHERE 
                     Opportunity__c = :q.Opportunity__c 
                    ];    
        }
        Quote q = [SELECT OpportunityId FROM Quote WHERE Id = :quoteId];
        return [ SELECT Segment__r.Name FROM Opportunity_Segment__c WHERE Opportunity__c = :q.OpportunityId ];
    }
    @AuraEnabled
    public static Map<String, Map<String, List<sObject> >> getContractInvoice( Id contractId ){
        try {
            Map<String, Map<String, List<sObject> >> allRecordMap = new Map<String, Map<String, List<sObject> >>();
            Map<String, List<sObject>> invRecMap = new Map<String, List<sObject>>();
            invRecMap.put( 'Invoices', [ SELECT Id, IO__r.Opportunity__r.Segment_Name__c, End_Date__c, Start_Date__c, Proposal__c, IO__r.Flight__c, IO__r.Campaign_Name__c,
                Client_Campaign_Name__c,
                ( SELECT Sales_Price__c, Data_Source__c, Product__r.name, Invoice__c,
                Counts__c, CPM__c, Impression__c, Monthly_Frequency__c, Trade_Desk_Campaign__c
                FROM Invoice_Line_Items__r ),
                ( SELECT Segment__r.Name 
                FROM Opportunity_Segments__r )
                FROM Invoice__c WHERE 
                IO__c = :contractId 
                ORDER BY End_Date__c
            ] );
            Set<Id> ioLItemIds = new Set<Id>();
            Set<Id> invIds = new Set<Id>();
            system.debug(contractId);
            for( Invoice__c inv : [SELECT Id FROM Invoice__c WHERE IO__c = :contractId ] ){
                system.debug(contractId);
                invIds.add( inv.Id );
            }
            for( Invoice_Line_Item__c invL : [SELECT Id FROM Invoice_Line_Item__c WHERE Invoice__c IN :invIds]  ){
                ioLItemIds.add( invL.Id );
            }
            Map<String, List<sObject>> ioSegmentsMap = new Map<String, List<sObject>>();
            for( Opportunity_Segment__c oppSeg :[SELECT Id, Segment__r.Name, IO_Invoice_Line_Item__c FROM Opportunity_Segment__c 
                                                 WHERE IO_Invoice_Line_Item__c IN :ioLItemIds
                                                ] ){
                                                    if( !ioSegmentsMap.containsKey( oppSeg.IO_Invoice_Line_Item__c ) ){
                                                        ioSegmentsMap.put( oppSeg.IO_Invoice_Line_Item__c, new List<sObject>() );
                                                    }
                                                    ioSegmentsMap.get(oppSeg.IO_Invoice_Line_Item__c).add( oppSeg );
            }
            allRecordMap.put( 'Invoice Recs', invRecMap );
            allRecordMap.put( 'Segments', ioSegmentsMap );
            return allRecordMap;
            /* return [ SELECT Id, IO__r.Opportunity__r.Segment_Name__c, End_Date__c, Start_Date__c, Proposal__c, IO__r.Flight__c, IO__r.Campaign_Name__c,
                     Client_Campaign_Name__c,
                     ( SELECT Sales_Price__c, Product__r.name, Invoice__c,
                     Counts__c, CPM__c, Impression__c, Monthly_Frequency__c 
                     FROM Invoice_Line_Items__r ),
                     ( SELECT Segment__r.Name 
                     FROM Opportunity_Segments__r )
                     FROM Invoice__c WHERE 
                     IO__c = :contractId 
                     ORDER BY End_Date__c
                    ]; */
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static String saveInvoice( List<Proposal_Invoice__c> invRecs, List<QuoteLineItem> lItemRecs, List<Id> delRecsIds ){
        System.debug( invRecs );
        System.debug(  lItemRecs );
        Map<Id, Proposal_Invoice__c> idPInvoiceMap = new Map<Id, Proposal_Invoice__c>();
        Map<String, Proposal_Invoice__c> newIdPInvoiceMap = new Map< String, Proposal_Invoice__c >(); 
        for( Proposal_Invoice__c pInvoice : invRecs ){
            try{
                idPInvoiceMap.put( pInvoice.Id, pInvoice );
            }catch( Exception e ){
                String i = String.valueOf(pInvoice.Id);
                newIdPInvoiceMap.put( i, pInvoice );
                pInvoice.Id = null;
            }
        }
        System.debug( newIdPInvoiceMap );
        for( QuoteLineItem lItem : lItemRecs ){
            if( newIdPInvoiceMap.containsKey( String.valueOf(lItem.Proposal_Invoice__c) ) ){
                lItem.Proposal_Invoice__r = newIdPInvoiceMap.get( String.valueOf(lItem.Proposal_Invoice__c) );
                lItem.Proposal_Invoice__c = null;
            } 
        }
        if( invRecs.size() > 0 ){
            UPSERT invRecs;
        }
        if( lItemRecs.size() > 0 ){
            for( QuoteLineItem lItem : lItemRecs ){
                if( lItem.Proposal_Invoice__c == null ){
                    lItem.Proposal_Invoice__c = lItem.Proposal_Invoice__r.Id;
                }
            }
            UPSERT lItemRecs;
        }
        
        if( delRecsIds.size() > 0 ){
            DELETE [SELECT Id FROM QuoteLineItem WHERE Id IN :delRecsIds];
        }
        return 'Success';
    }
    @AuraEnabled
    public static Map<String, Id> saveIOInvoice(List<Invoice__c> invRecs, List<Invoice_Line_Item__c> lItemRecs, List<Id> delRecsIds, List<Opportunity_Segment__c> newSegs, List<String> nProdSeg ){
        System.debug( ';;'+nProdSeg );
        try{
            //List<Opportunity_Segment__c> nSegments = (List<Opportunity_Segment__c>) System.JSON.deserialize(newSegs, List<Opportunity_Segment__c>.Class);
            Map<Id, Invoice__c> idPInvoiceMap = new Map<Id, Invoice__c>();
            Map<String, Invoice__c> newIdPInvoiceMap = new Map< String, Invoice__c >();
            Map<String, Invoice_Line_Item__c> lItemIdMap = new Map<String, Invoice_Line_Item__c>();
            Map<String, Id> lItemIdMap2 = new Map<String, Id>();
            System.debug(newSegs);

            for( Invoice__c pInvoice : invRecs ){
                try{
                    idPInvoiceMap.put( pInvoice.Id, pInvoice );
                }catch( Exception e ){
                    String i = String.valueOf(pInvoice.Id);
                    newIdPInvoiceMap.put( i, pInvoice );
                    pInvoice.Id = null;
                }
            }
            System.debug( newIdPInvoiceMap );
            for( Invoice_Line_Item__c lItem : lItemRecs ){
                String lItemId = lItem.Id+'';
                System.debug(lItemId);
                if( lItemId.length() < 10 ){
                    lItemIdMap.put( lItemId, lItem );
                    lItem.Id = null;
                }
                if( newIdPInvoiceMap.containsKey( String.valueOf(lItem.Invoice__c) ) ){
                    lItem.Invoice__r = newIdPInvoiceMap.get( String.valueOf(lItem.Invoice__c) );
                    System.debug( '--------' );
                    System.debug( lItem.Invoice__c );
                    System.debug( lItem.Id );
                    lItem.Invoice__c = null;
                } 
            }
            for( Opportunity_Segment__c lItem : newSegs ){
                if( newIdPInvoiceMap.containsKey( String.valueOf(lItem.IO_Invoice__c) ) ){
                    lItem.IO_Invoice__r = newIdPInvoiceMap.get( String.valueOf(lItem.IO_Invoice__c) );
                    lItem.IO_Invoice__c = null;
                } 
            }
            if( invRecs.size() > 0 ){
                UPSERT invRecs;
            }
            if( lItemRecs.size() > 0 ){
                for( Invoice_Line_Item__c lItem : lItemRecs ){
                    if( lItem.Invoice__c == null ){
                        lItem.Invoice__c = lItem.Invoice__r.Id;
                    }
                }
                UPSERT lItemRecs;
                for( String i : lItemIdMap.keySet() ){
                    Invoice_Line_Item__c invL = lItemIdMap.get( i );
                    lItemIdMap2.put( i, invL.Id );
                }
            } 
            if( newSegs.size() > 0 ){
                for( Opportunity_Segment__c lItem : newSegs ){
                    if( lItem.IO_Invoice__c == null ){
                        lItem.IO_Invoice__c = lItem.IO_Invoice__r.Id;
                    }
                }
                System.debug(newSegs);
                UPSERT newSegs;
            } 
            if( delRecsIds.size() > 0 ){
                DELETE [SELECT Id FROM Invoice_Line_Item__c WHERE Id IN :delRecsIds];
            }
            return lItemIdMap2;
        }catch( AuraHandledException e ){
            System.debug( e.getMessage() );
            throw new AuraHandledException(e.getMessage());
        }
        
        /* try {
            if( invRecs.size() > 0 ){
                UPSERT invRecs;
            }
            if( lItemRecs.size() > 0 ){
                UPSERT lItemRecs;
            }
            return 'Success';
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        } */
    }
    @AuraEnabled
    public static List<Product2> getProducts( Id quoteId, String objName ){
        try {
            if( objName == 'Quote' ){
                Quote cont = [ SELECT Opportunity.Pricebook2Id FROM Quote WHERE Id = :quoteId ];
                if( cont.Opportunity.Pricebook2Id != null ){
                    Set<Id> prodIds = new Set<Id>();
                    for( PricebookEntry pEntry : [SELECT Id, Name, Product2Id, UnitPrice from PricebookEntry WHERE Pricebook2Id = :cont.Opportunity.Pricebook2Id] ){
                        prodIds.add( pEntry.Product2Id );
                    }
                    return [SELECT Name FROM Product2 WHERE Id IN :prodIds];
                }
            }else{
                Contract cont = [ SELECT Opportunity__r.Pricebook2Id FROM Contract WHERE Id = :quoteId ];
                if( cont.Opportunity__r.Pricebook2Id != null ){
                    Set<Id> prodIds = new Set<Id>();
                    for( PricebookEntry pEntry : [SELECT Id, Name, Product2Id, UnitPrice from PricebookEntry WHERE Pricebook2Id = :cont.Opportunity__r.Pricebook2Id] ){
                        prodIds.add( pEntry.Product2Id );
                    }
                    return [SELECT Name FROM Product2 WHERE Id IN :prodIds];
                }
            }
            return null;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static List<OpportunityLineItem> getOppProds(Id quoteId, String objName){
        try {
            if( objName == 'Quote' ){
                Quote q = [SELECT Id, OpportunityId FROM Quote WHERE Id = :quoteId LIMIT 1];
                return  [SELECT Id, UnitPrice, ListPrice, Product2.Name,
                        Quantity, Monthly_Frequency__c, Impression__c 
                        FROM OpportunityLineItem
                        WHERE OpportunityId = :q.OpportunityId
                        ];
            }else{
                Contract q = [SELECT Id, Opportunity__c FROM Contract WHERE Id = :quoteId LIMIT 1];
                return  [SELECT Id, UnitPrice, ListPrice, Product2.Name,
                        Quantity, Monthly_Frequency__c, Impression__c 
                        FROM OpportunityLineItem
                        WHERE OpportunityId = :q.Opportunity__c
                        ];
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    //For multiple lookup

    @AuraEnabled(cacheable=true)
    public static List<SObJectResult> getAllSegments( String value, List<String> selectedRecId ) {
        List<SObJectResult> sObjectResultList = new List<SObJectResult>();
        System.debug( 'VALS:'+selectedRecId+', ->'+value );
        if(selectedRecId == null)
            selectedRecId = new List<String>();
        /* system.debug(fieldName+'-------------'+ObjectName+'---++----------'+value+'====='+selectedRecId);
        

        if(String.isNotEmpty(value)) {
            String query = 'Select Id';
            if(useFilterCriteria){
                query = query+ fieldName+' FROM '+ObjectName+' WHERE NAME LIKE \'%' + value.trim() + '%\' and ID NOT IN: selectedRecId ';
                query = query+' and '+filterField+'= \''+filterFieldValue+'\'';

            }else{
                query = query+', Name FROM '+ObjectName+' WHERE NAME LIKE \'%' + value.trim() + '%\' and ID NOT IN: selectedRecId';
            }
            system.debug(query);
            String fieldvalue = ''; */
            String query='';
        if(String.isNotEmpty(value)) {  
            query = 'SELECT Id, Name FROM Segment__c WHERE NAME LIKE \'%' + value.trim() + '%\' and ID NOT IN: selectedRecId';
        }else{
            query = 'SELECT Id, Name FROM Segment__c WHERE ID NOT IN: selectedRecId';
        }
        for(sObject so : Database.Query(query)) {
            String fieldvalue = (String)so.get('Name');
            sObjectResultList.add(new SObjectResult(fieldvalue, so.Id));
        }
        return sObjectResultList;
    }

    @AuraEnabled
    public static List<Invoice__c> getContractInvoiceStartEnd( Id contractId, Date sDate, Date eDate ){
        try {   
            System.debug( '-->'+sDate+':'+ eDate );
            return [ SELECT Id, IO__r.Opportunity__r.Segment_Name__c, End_Date__c, Start_Date__c, Proposal__c, IO__r.Flight__c, IO__r.Campaign_Name__c,
                     Client_Campaign_Name__c,
                     ( SELECT Sales_Price__c, Product__r.name, Invoice__c,
                     Counts__c, CPM__c, Impression__c, Monthly_Frequency__c 
                     FROM Invoice_Line_Items__r )
                     FROM Invoice__c WHERE 
                     IO__c = :contractId AND Start_Date__c >= :sDate AND End_Date__c <=:eDate
                    ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<SObJectResult> getResults(String ObjectName, String fieldName, String value, List<String> selectedRecId) {
        List<SObJectResult> sObjectResultList = new List<SObJectResult>();
        if(String.isNotEmpty(value)) {
            String query = 'Select Id, Name FROM Segment__c WHERE Name LIKE \'%' + value.trim() + '%\'';
            system.debug(query);
            for(sObject so : Database.Query(query)) {
                String fieldvalue = (String)so.get('Name');
                sObjectResultList.add(new SObjectResult(fieldvalue, so.Id));
            }
        }
        return sObjectResultList;
    }
    @AuraEnabled
    public static void createNewSegments( String newSegs ){
        try {
            System.debug( 'SS:'+newSegs );
            Map<String, Object> resMap = (Map<String, Object>)json.deserializeUntyped(newSegs);
            List<Opportunity_Segment__c> oppSegs = new List<Opportunity_Segment__c>();
            Set<Id> invIds = new Set<Id>();
            for( String key : resMap.keySet() ){
                List<Object> oppSegs2 = (List<Object>) resMap.get( key );
                for( Object opS : oppSegs2 ){
                    Map<string, Object> oppSe = (Map<string, Object>) opS;
                    String oppSegId = (String)oppSe.get('IO_Invoice_Line_Item__c');
                    if( oppSegId.length() > 10 ){
                        invIds.add( (Id)oppSe.get('IO_Invoice_Line_Item__c') );
                        if( (String)oppSe.get('Segment__c') != null ){
                            oppSegs.add( new Opportunity_Segment__c(Segment__c=(String)oppSe.get('Segment__c'), IO_Invoice_Line_Item__c = (Id)oppSe.get('IO_Invoice_Line_Item__c') ));
                        }    
                    }
                } 
            }
            if( invIds.size() > 0 ){
                System.debug('-->:'+oppSegs);
                DELETE [SELECT Id FROM Opportunity_Segment__c WHERE IO_Invoice_Line_Item__c IN :invIds];
                System.debug('Deleted');
                Set<Id> remInvId = new Set<Id>();
                for( Invoice_Line_Item__c invL : [SELECT Id FROM Invoice_Line_Item__c WHERE Id IN :invIds] ){
                    remInvId.add( invL.Id );
                }
                List<Opportunity_Segment__c> newOppSegs = new List<Opportunity_Segment__c>();
                for( Opportunity_Segment__c oppseg : oppSegs ){
                    if( remInvId.contains( oppseg.IO_Invoice_Line_Item__c ) ){
                        newOppSegs.add( oppseg );
                    }
                }
                if( newOppSegs.size() > 0 ){
                    System.debug('-->:'+newOppSegs);
                    INSERT newOppSegs;
                }
            }
            System.debug( oppSegs + '-->'+ invIds );
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    public class SObjectResult {
        @AuraEnabled
        public String recName;
        @AuraEnabled
        public Id recId;
        
        public SObJectResult(String recNameTemp, Id recIdTemp) {
            recName = recNameTemp;
            recId = recIdTemp;
        }
        public SObJectResult() {
          
        }
    }
}