force-app/main/default/objects/Contract/fields/Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Name__c</fullName>
    <formula>Opportunity__r.Account.Name + &apos;-&apos; +  Opportunity__r.SubClient_or_Manufacturer__r.Name + &apos;-&apos; +  Opportunity__r.Name + &apos;-&apos; +  TEXT( Opportunity__r.Audience_Type__c )</formula>
    <label>Campaign Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>IO Invoice</label>
    <nameField>
        <displayFormat>INV-{000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IO Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/IO__c.field-meta.xml
<CustomField>
    <fullName>IO__c</fullName>
    <label>IO</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>IO Invoices</relationshipLabel>
    <relationshipName>Contract_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>IO Invoice Line Item</label>
    <nameField>
        <displayFormat>INVL-{000}</displayFormat>
        <label>Invoice Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IO Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/IO__c.field-meta.xml
<CustomField>
    <fullName>IO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IO</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>IO Invoice Line Items</relationshipLabel>
    <relationshipName>IO_Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Iterable_Campaign_Id__c.field-meta.xml
<CustomField>
    <fullName>Iterable_Campaign_Id__c</fullName>
    <label>Iterable Campaign Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreateCampaignToExtBatch.cls
public class CreateCampaignToExtBatch implements Database.Batchable<sObject>, Database.AllowsCallouts{
    List<Invoice__c> ioInvoices = new List<Invoice__c>();
    public CreateCampaignToExtBatch( List<Invoice__c> campNames ){
        ioInvoices = campNames;
    }
    public List<Invoice__c> start( Database.BatchableContext bc ){
        return ioInvoices;
    }	
    public void execute( Database.BatchableContext bc, List<Invoice__c> ioInvoicesIte ){
        Map<String, String> cNameIterableIdMap = new Map<String, String>();
        Set<String> campaignsName = new Set<String>();
        List<Invoice_Line_Item__c> invLItems = new List<Invoice_Line_Item__c>();
        for( Invoice__c inv : ioInvoicesIte){
            for( Invoice_Line_Item__c invLItem : inv.Invoice_Line_Items__r ){
                if( invLItem.Iterable_Campaign_Id__c == null )
                    campaignsName.add( inv.IO__r.Campaign_Name__c+'-'+invLItem.Product__r.Name+'-IO#'+inv.IO__r.ContractNumber ); 	   
            }
        }
        for( String cName : campaignsName ){
            Http h = new Http();
            HttpRequest req = new HttpRequest();
            req.setEndpoint('https://api.iterable.com/api/campaigns/create');
            req.setMethod('POST');
            req.setHeader('Api_Key', '32ff9424befa448ab59848bc48305267');
            req.setBody('{"name": "'+cName+'","listIds": [1861940],"templateId": 6775759}');
            HttpResponse res = h.send( req );
            System.debug(res.getBody());
            Map<String, Object> resMap = ( Map<String, Object> )JSON.deserializeUntyped(res.getBody());
            Integer cId = (Integer)resMap.get( 'campaignId' );
            cNameIterableIdMap.put( cName, String.valueOf(cId) );
        }
        for( Invoice__c inv : ioInvoicesIte){
            for( Invoice_Line_Item__c invLItem : inv.Invoice_Line_Items__r ){
                if( cNameIterableIdMap.containsKey( inv.IO__r.Campaign_Name__c+'-'+invLItem.Product__r.Name+'-IO#'+inv.IO__r.ContractNumber ) ){
                    invLItem.Iterable_Campaign_Id__c = cNameIterableIdMap.get( inv.IO__r.Campaign_Name__c+'-'+invLItem.Product__r.Name+'-IO#'+inv.IO__r.ContractNumber );
                    invLItems.add( invLItem ); 	   
                }
            }
        }
        if( invLItems.size() > 0 ){
            UPDATE invLItems;
        }
    }	
    public void finish( Database.BatchableContext bc ){
        
    }
}