force-app/main/default/objects/Contract/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>IO</relationshipLabel>
    <relationshipName>IO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposal</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>IO</relationshipLabel>
    <relationshipName>IO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>IO Invoice</label>
    <nameField>
        <displayFormat>INV-{000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IO Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/IO__c.field-meta.xml
<CustomField>
    <fullName>IO__c</fullName>
    <label>IO</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>IO Invoices</relationshipLabel>
    <relationshipName>Contract_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Invoice</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposal</label>
    <referenceTo>Quote</referenceTo>
    <relationshipName>Invoice</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <label>Total Price</label>
    <summarizedField>Invoice_Line_Item__c.Sales_Price__c</summarizedField>
    <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>IO Invoice Line Item</label>
    <nameField>
        <displayFormat>INVL-{000}</displayFormat>
        <label>Invoice Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IO Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Ad_Sizes__c.field-meta.xml
<CustomField>
    <fullName>Ad_Sizes__c</fullName>
    <label>Ad Sizes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Counts__c.field-meta.xml
<CustomField>
    <fullName>Counts__c</fullName>
    <label>Counts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/CPM__c.field-meta.xml
<CustomField>
    <fullName>CPM__c</fullName>
    <label>CPM</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/IO__c.field-meta.xml
<CustomField>
    <fullName>IO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IO</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>IO Invoice Line Items</relationshipLabel>
    <relationshipName>IO_Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Monthly_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Frequency__c</fullName>
    <label>Monthly Frequency</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <label>Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <formula>Quantity__c*Sales_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Flight_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Flight_End_Date__c</fullName>
    <label>Flight End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Flight_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Flight_Start_Date__c</fullName>
    <label>Flight Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <errorMessage>Contact should be under the same account</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Brand__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.SubClient_or_Manufacturer__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Monthly_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Frequency__c</fullName>
    <defaultValue>30</defaultValue>
    <label>Monthly Frequency</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_Id__c</fullName>
    <externalId>true</externalId>
    <label>Product Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proposal_Invoice__c/Proposal_Invoice__c.object-meta.xml
<CustomObject>
    <label>Proposal Invoice</label>
    <nameField>
        <displayFormat>PIN-{000}</displayFormat>
        <label>Proposal Inovice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposal Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal_Invoice__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <label>Proposal</label>
    <referenceTo>Quote</referenceTo>
    <relationshipName>Proposal_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Flight_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Flight_End_Date__c</fullName>
    <label>Flight End Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Flight_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Flight_Start_Date__c</fullName>
    <label>Flight Start Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <label>Total Price</label>
    <summarizedField>Proposal_Invoice__c.Total_Price__c</summarizedField>
    <summaryForeignKey>Proposal_Invoice__c.Proposal__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Ad_Sizes__c.field-meta.xml
<CustomField>
    <fullName>Ad_Sizes__c</fullName>
    <label>Ad Sizes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Counts__c.field-meta.xml
<CustomField>
    <fullName>Counts__c</fullName>
    <label>Counts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/CPM__c.field-meta.xml
<CustomField>
    <fullName>CPM__c</fullName>
    <label>CPM</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Monthly_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Frequency__c</fullName>
    <label>Monthly Frequency</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Proposal_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposal Invoice</label>
    <referenceTo>Proposal_Invoice__c</referenceTo>
    <relationshipLabel>Proposal Line Items</relationshipLabel>
    <relationshipName>Proposal_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProposalTriggerHelper.cls
public class ProposalTriggerHelper {
    public static void createProposalInvoices( List<Quote> proposals ){
        Set<Id> oppIds = new Set<Id>();
        List<Opportunity> oppStageChange = new List<Opportunity>();
        List<Proposal_Invoice__c> invoices = new List<Proposal_Invoice__c>();
        List<QuoteLineItem> invLItems = new List<QuoteLineItem>();
        for( Quote proposal : proposals ){
            oppIds.add( proposal.OpportunityId );
        }
        Map<Id, List<OpportunityLineItem>> oppLItemMap = new Map<Id, List<OpportunityLineItem>>();
        for( OpportunityLineItem oppLItem : [SELECT Discount, Ad_Sizes__c, OpportunityId, ListPrice, Monthly_Frequency__c, UnitPrice, PricebookEntryId, Product2Id, Product2.Name, product2.Product_Id__c, Quantity, TotalPrice FROM OpportunityLineItem WHERE OpportunityId IN :oppIds] ){
            if( !oppLItemMap.containsKey(oppLItem.OpportunityId) ){
                oppLItemMap.put( oppLItem.OpportunityId, new List<OpportunityLineItem>() );
            }
            oppLItemMap.get(oppLItem.OpportunityId).add( oppLItem );
        }
        for( Quote proposal : proposals ){
            //Change opp stage
            Opportunity opp = new Opportunity( Id = proposal.OpportunityId, StageName='Proposal' );
            oppStageChange.add( opp );
            
            //Create IO
            DateTime dt = proposal.Flight_Start_Date__c;
            Date startDate = Date.newInstance(dt.year(), dt.month(), dt.day());
            dt = proposal.Flight_End_Date__c;
            Date endDate = Date.newInstance(dt.year(), dt.month(), dt.day());
            Integer contractTerm = startDate.monthsBetween(endDate);
            
            List<OpportunityLineItem> opplItems = oppLItemMap.get( proposal.OpportunityId );
            
            for( integer i = 0; i<contractTerm; i++ ){
                Integer numberOfDays = Date.daysInMonth(startDate.year(), startDate.month());
                endDate = startDate.addDays(numberOfDays - startDate.day());
                Proposal_Invoice__c invoice = new Proposal_Invoice__c( Proposal__c = proposal.Id, Start_Date__c = startDate, End_Date__c = endDate );
                startDate = endDate.addDays( 1 );
                
                if( opplItems != null ){
                    for( OpportunityLineItem pItem : opplItems ){
                        QuoteLineItem invLItem = new QuoteLineItem();
                        invLItem.Discount = pItem.Discount;
                        invLItem.Proposal_Invoice__r = invoice;
                        invLItem.Quantity = pItem.Quantity;
                        invLItem.Monthly_Frequency__c = pItem.Monthly_Frequency__c;
                        invLItem.CPM__c = pItem.ListPrice;
                        invLItem.Ad_Sizes__c = pItem.Ad_Sizes__c;
                        invLItem.Product2Id = pItem.Product2Id;
                        //invLItem.Quantity = pItem.Quantity;
                        invLItem.UnitPrice = pItem.UnitPrice;
                        invLItem.QuoteId = proposal.Id;
                        invLItem.PricebookEntryId = pItem.PricebookEntryId;
                        invLItems.add( invLItem );
                    }   
                }
                invoices.add( invoice );
            }
        }
        if( oppStageChange.size() > 0 ){
            UPDATE oppStageChange;
        }
        
        if( invoices.size() > 0 ){
            INSERT invoices;
            if( invLItems.size() > 0 ){
                for( QuoteLineItem invLItem : invLItems ){
                    invLItem.Proposal_Invoice__c = invLItem.Proposal_Invoice__r.Id;
                }
                INSERT invLItems;
            }
        }
        
    }
    static void createInovices( String lineItemPObj, List<sObject> proposals, String lItemCopy ){
        /*Set<Id> proposalIds = new Set<Id>();
List<sObject> contracts = new List<sObject>();
List<sObject> invoices = new List<sObject>();
List<sObject> invLItems = new List<sObject>();
//Creating map of Proposal Id and Line items
for( Quote proposal : proposals ){
proposalIds.add( proposal.OpportunityId );
}
Map<Id, List<sObject>> quoteIdLItemMap = new Map<Id, List<sObject>>();
proposals = Database.query('[ SELECT Id, Status, Pricebook2Id, OpportunityId, Flight_Start_Date__c, Flight_End_Date__c, Opportunity.AccountId, Opportunity.Primary_Contact__c FROM Quote WHERE Id IN :proposalIds ]');
for( QuoteLineItem qLItem : [SELECT Discount, QuoteId, UnitPrice, PricebookEntryId, Product2Id, Product2.Name, product2.Product_Id__c, Quantity, TotalPrice FROM QuoteLineItem WHERE QuoteId IN :proposalIds] ){
if( !quoteIdLItemMap.containsKey(qLItem.QuoteId) ){
quoteIdLItemMap.put( qLItem.QuoteId, new List<QuoteLineItem>() );
}
quoteIdLItemMap.get(qLItem.QuoteId).add( qLItem );
}

for( Quote proposal : proposals ){
if( proposal.Status == 'Accepted' ){
//Change opp stage
Opportunity opp = new Opportunity( Id = proposal.OpportunityId, StageName='Closed Won' );
oppStageChange.add( opp );

//Create IO
DateTime dt = proposal.Flight_Start_Date__c;
Date startDate = Date.newInstance(dt.year(), dt.month(), dt.day());
dt = proposal.Flight_End_Date__c;
Date endDate = Date.newInstance(dt.year(), dt.month(), dt.day());
Integer contractTerm = startDate.monthsBetween(endDate);
Contract cont = new Contract( AccountId = proposal.Opportunity.AccountId, StartDate = startDate, ContractTerm = contractTerm, CustomerSignedId = proposal.Opportunity.Primary_Contact__c, Proposal__c = proposal.Id ); 
contracts.add( cont );

//Creating Orders/Invoice and Invoice Line Items
List<QuoteLineItem> proposalItems = quoteIdLItemMap.get( proposal.Id );
for( integer i = 0; i<contractTerm; i++ ){
Invoice__c invoice = new Invoice__c( IO__r = cont, Start_Date__c = startDate );
startDate = startDate.addMonths( 1 );
invoice.End_Date__c = startDate.addDays(-1);   
for( QuoteLineItem pItem : proposalItems ){
Invoice_Line_Item__c invLItem = new Invoice_Line_Item__c();
invLItem.Discount__c = pItem.Discount;
invLItem.Invoice__r = invoice;
invLItem.Product__c = pItem.Product2Id;
invLItem.Quantity__c = pItem.Quantity;
invLItem.Sales_Price__c = pItem.UnitPrice;
invLItem.Total_Price__c = pItem.TotalPrice;
invLItems.add( invLItem );
}
invoices.add( invoice );
}
}
}
if( oppStageChange.size() > 0 ){
UPDATE oppStageChange;
}
if( contracts.size() > 0 ){
INSERT contracts;
if( invoices.size() > 0 ){
for( Invoice__c invoice : invoices ){
invoice.IO__c = invoice.IO__r.Id;
}
INSERT invoices;
if( invLItems.size() > 0 ){
for( Invoice_Line_Item__c invLItem : invLItems ){
invLItem.Invoice__c = invLItem.Invoice__r.Id;
}
INSERT invLItems;
}
}
}*/
    }
    public static void createIO( List<Quote> proposals, Map<Id, Quote> proposalMap ){
        List<Opportunity> oppStageChange = new List<Opportunity>();
        Set<Id> proposalIds = new Set<Id>();
        Set<Id> pInvoiceIds = new Set<Id>();
        List<Contract> contracts = new List<Contract>();
        List<Invoice__c> invoices = new List<Invoice__c>();
        List<Invoice_Line_Item__c> invLItems = new List<Invoice_Line_Item__c>();
        //Creating map of Proposal Id and Line items
        for( Quote proposal : proposals ){
            if( proposal.Status == 'Accepted' && proposalMap.get( proposal.Id ).Status != 'Accepted' ){
                proposalIds.add( proposal.Id );
                Opportunity opp = new Opportunity( Id = proposal.OpportunityId, StageName='IO Initiated' );
                oppStageChange.add( opp );
            }else if( proposal.Status == 'Denied' && proposalMap.get( proposal.Id ).Status != 'Denied' ){
                Opportunity opp = new Opportunity( Id = proposal.OpportunityId, StageName='Closed Lost' );
                oppStageChange.add( opp );
            }
        }
        Map<Id, List<QuoteLineItem>> quoteIdLItemMap = new Map<Id, List<QuoteLineItem>>();
        Map<Id, List<Proposal_Invoice__c>> quoteIdPInvoiceMap = new Map<Id, List<Proposal_Invoice__c>>();
        Map<Id, List<QuoteLineItem>> pInvIdPItemMap = new Map<Id, List<QuoteLineItem>>();
        
        proposals = [ SELECT Id, Status, Pricebook2Id, OpportunityId, Flight_Start_Date__c, Flight_End_Date__c, Opportunity.AccountId, Opportunity.Primary_Contact__c FROM Quote WHERE Id IN :proposalIds ];
        
        for( Proposal_Invoice__c pInvoice : [SELECT Start_Date__c, Proposal__c, End_Date__c FROM Proposal_Invoice__c WHERE Proposal__c IN :proposalIds] ){
            if( !quoteIdPInvoiceMap.containsKey(pInvoice.Proposal__c) ){
                quoteIdPInvoiceMap.put( pInvoice.Proposal__c, new List<Proposal_Invoice__c>() );
            }
            pInvoiceIds.add( pInvoice.Id );
            quoteIdPInvoiceMap.get(pInvoice.Proposal__c).add( pInvoice );
        }
        for( QuoteLineItem qLItem : [SELECT Discount, CPM__c, Monthly_Frequency__c, Ad_Sizes__c, Proposal_Invoice__c, QuoteId, UnitPrice, PricebookEntryId, Product2Id, Product2.Name, product2.Product_Id__c, Quantity, TotalPrice FROM QuoteLineItem WHERE Proposal_Invoice__c IN :pInvoiceIds] ){
            if( !pInvIdPItemMap.containsKey(qLItem.Proposal_Invoice__c) ){
                pInvIdPItemMap.put( qLItem.Proposal_Invoice__c, new List<QuoteLineItem>() );
            }
            pInvIdPItemMap.get(qLItem.Proposal_Invoice__c).add( qLItem );
        }
        for( Quote proposal : proposals ){
            if( proposal.Status == 'Accepted' && proposalMap.get( proposal.Id ).Status != 'Accepted' ){
                
                //Create IO
                DateTime dt = proposal.Flight_Start_Date__c;
                Date startDate = Date.newInstance(dt.year(), dt.month(), dt.day());
                dt = proposal.Flight_End_Date__c;
                Date endDate = Date.newInstance(dt.year(), dt.month(), dt.day());
                Integer contractTerm = startDate.monthsBetween(endDate);
                Contract cont = new Contract( AccountId = proposal.Opportunity.AccountId, Opportunity__c = proposal.OpportunityId, StartDate = startDate, ContractTerm = contractTerm, CustomerSignedId = proposal.Opportunity.Primary_Contact__c, Proposal__c = proposal.Id ); 
                contracts.add( cont );
                
                //Creating Orders/Invoice and Invoice Line Items
                /*if( quoteIdPInvoiceMap.containsKey( proposal.Id ) ){
                    List<Proposal_Invoice__c> proInvs = quoteIdPInvoiceMap.get( proposal.Id );
                    for( Proposal_Invoice__c proInv : proInvs ){
                        Invoice__c invoice = new Invoice__c( IO__r = cont, Start_Date__c = proInv.Start_Date__c, End_Date__c = proInv.End_Date__c );   
                        if( pInvIdPItemMap.containsKey(proInv.Id) ){
                            for( QuoteLineItem pItem : pInvIdPItemMap.get(proInv.Id) ){
                                Invoice_Line_Item__c invLItem = new Invoice_Line_Item__c();
                                invLItem.Discount__c = pItem.Discount;
                                invLItem.Ad_Sizes__c = pItem.Ad_Sizes__c;
                                invLItem.Counts__c = pItem.Counts__c;
                                invLItem.CPM__c = pItem.CPM__c;
                                invLItem.Monthly_Frequency__c = pItem.Monthly_Frequency__c;
                                invLItem.Invoice__r = invoice;
                                invLItem.Product__c = pItem.Product2Id;
                                invLItem.Quantity__c = pItem.Quantity;
                                invLItem.Sales_Price__c = pItem.UnitPrice;
                                invLItems.add( invLItem );
                            }    
                        }
                        invoices.add( invoice );       
                    }    
                }*/
            }
        }
        if( oppStageChange.size() > 0 ){
            UPDATE oppStageChange;
        }
        if( contracts.size() > 0 ){
            INSERT contracts;
            /*if( invoices.size() > 0 ){
                for( Invoice__c invoice : invoices ){
                    invoice.IO__c = invoice.IO__r.Id;
                }
                INSERT invoices;
                if( invLItems.size() > 0 ){
                    for( Invoice_Line_Item__c invLItem : invLItems ){
                        invLItem.Invoice__c = invLItem.Invoice__r.Id;
                    }
                    INSERT invLItems;
                }
            }*/
        }
    }
}