force-app/main/default/objects/Contract/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>IO</relationshipLabel>
    <relationshipName>IO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>IO Invoice</label>
    <nameField>
        <displayFormat>INV-{000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IO Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/IO__c.field-meta.xml
<CustomField>
    <fullName>IO__c</fullName>
    <label>IO</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>IO Invoices</relationshipLabel>
    <relationshipName>Contract_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Invoice</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>IO Invoice Line Item</label>
    <nameField>
        <displayFormat>INVL-{000}</displayFormat>
        <label>Invoice Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IO Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Counts__c.field-meta.xml
<CustomField>
    <fullName>Counts__c</fullName>
    <label>Counts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/CPM__c.field-meta.xml
<CustomField>
    <fullName>CPM__c</fullName>
    <label>CPM</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Impression__c.field-meta.xml
<CustomField>
    <fullName>Impression__c</fullName>
    <formula>( Sales_Price__c  /  CPM__c )*1000</formula>
    <label>Impression</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/IO__c.field-meta.xml
<CustomField>
    <fullName>IO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IO</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>IO Invoice Line Items</relationshipLabel>
    <relationshipName>IO_Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Monthly_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Frequency__c</fullName>
    <label>Monthly Frequency</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <label>Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_Segment__c/Opportunity_Segment__c.object-meta.xml
<CustomObject>
    <label>Opportunity Segment</label>
    <nameField>
        <displayFormat>OS-{000}</displayFormat>
        <label>Opportunity Segment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Segments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Segment__c/fields/IO_Invoice__c.field-meta.xml
<CustomField>
    <fullName>IO_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IO Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Opportunity Segments</relationshipLabel>
    <relationshipName>Opportunity_Segments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Segment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Segments</relationshipLabel>
    <relationshipName>Opportunity_Segments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Segment__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segment</label>
    <referenceTo>Segment__c</referenceTo>
    <relationshipLabel>Opportunity Segments</relationshipLabel>
    <relationshipName>Opportunity_Segments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Segment__c/Segment__c.object-meta.xml
<CustomObject>
    <label>Segment</label>
    <nameField>
        <label>Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/IOInvoiceLineItemTriggerHelper.cls
public class IOInvoiceLineItemTriggerHelper {
    public static boolean start = false;
    public static void createInvoiceINQB( List<Invoice_Line_Item__c> newIoInvoices ){
        
    }
    public static void createSegments( Map<Id,Invoice_Line_Item__c> invsMap ){
        system.debug('invsMap===>'+invsMap);
        Set<Id> oppIds = new Set<ID>();
        List<Invoice_Line_Item__c> invs = [SELECT Invoice__r.IO__r.Opportunity__c FROM Invoice_Line_Item__c WHERE Id IN :invsMap.keySet()];
        system.debug('invs===>'+invs);
        for( Invoice_Line_Item__c inv : invs ){
            oppIds.add( inv.Invoice__r.IO__r.Opportunity__c );
        }
        system.debug('oppIds===>'+oppIds);
        Map<Id, List<Opportunity_Segment__c> > oppIdSegMap = new Map<Id, List<Opportunity_Segment__c> >();
        for( Opportunity opp : [SELECT Id, ( SELECT Segment__c, Opportunity__c, IO_Invoice__c FROM Opportunity_Segments__r ) 
                                FROM Opportunity WHERE ID IN :oppIds] ){
                                    oppIdSegMap.put( opp.Id, opp.Opportunity_Segments__r );
                                }
        system.debug('oppIdSegMap===>'+oppIdSegMap);
        List<Opportunity_Segment__c> newSegs = new List<Opportunity_Segment__c>();
        for( Invoice_Line_Item__c inv : invs ){
            if( oppIdSegMap.containsKey( inv.Invoice__r.IO__r.Opportunity__c ) ){
                for( Opportunity_Segment__c oppSeg : oppIdSegMap.get(inv.Invoice__r.IO__r.Opportunity__c) ){
                    Opportunity_Segment__c opS = new Opportunity_Segment__c( Segment__c=oppSeg.Segment__c, IO_Invoice_Line_Item__c = inv.Id );
                    newSegs.add( opS );
                } 	   
            }
        }
        if( newSegs.size() > 0 ){
            INSERT newSegs;
        }
    }
    public static void createLineItemInNextInv( Map<Id,Invoice_Line_Item__c> invsMap ){
        List<Invoice_Line_Item__c> newIoInvoices = [SELECT Id, Sales_Price__c, Product__c, Invoice__c,
                                                    Counts__c, CPM__c, Impression__c, 
                                                    Monthly_Frequency__c  
                                                    FROM Invoice_Line_Item__c 
                                                    WHERE Id IN :invsMap.keySet()
                                                   ];
        Map<Id, List<Invoice_Line_Item__c>> invIdLItemMap = new Map<Id, List<Invoice_Line_Item__c>>();
        Map<Id, List<Id>> ioIdInvIdsMap = new Map<Id, List<Id>>();
        Map<Id, List<Id>> invIdNextInvIdMap = new Map<Id, List<Id>>();
        Set<Id> invIds = new Set<Id>();
        Set<Id> ioIds = new Set<Id>();
        for( Invoice_Line_Item__c ioInv : newIoInvoices ){
            invIds.add( ioInv.Invoice__c );
            if( !invIdLItemMap.containsKey(ioInv.Invoice__c) ){
                invIdLItemMap.put( ioInv.Invoice__c, new List<Invoice_Line_Item__c>() );
            }
            invIdLItemMap.get( ioInv.Invoice__c ).add( ioInv );
        }
        for( Invoice__c inv : [SELECT Id, IO__c FROM Invoice__c WHERE Id IN :invIds] ){
            ioIds.add( inv.IO__c );
        }
        for( Contract cont : [SELECT Id, (SELECT Id FROM Contract_Invoices__r) FROM Contract WHERE Id IN :ioIds] ){
            ioIdInvIdsMap.put( cont.Id, new List<Id>() );
            for( Invoice__c inv : cont.Contract_Invoices__r ){
            	ioIdInvIdsMap.get( cont.Id ).add( inv.Id );    
            }
        }
        for( Id ioId : ioIdInvIdsMap.keySet() ){
            boolean found = false;
            for( Id invId : ioIdInvIdsMap.get( ioId ) ){
                if( invIdLItemMap.containsKey( invId ) ){
                    invIdNextInvIdMap.put( invId, new List<Id>() );
                    fillNextInvIds( ioIdInvIdsMap.get( ioId ), invIdNextInvIdMap, invId );
                }
            }
        }
        system.debug('invIdNextInvIdMap==>'+invIdNextInvIdMap);
        List<Invoice_Line_Item__c> newInvLItems = new List<Invoice_Line_Item__c>();
        for( Id invId : invIdLItemMap.keySet() ){
            for( Invoice_Line_Item__c invLItem : invIdLItemMap.get( invId ) ){
                for( Id nextInvId : invIdNextInvIdMap.get( invId ) ){
                    System.debug('==>>'+nextInvId);
                    Invoice_Line_Item__c newInvLItem = new Invoice_Line_Item__c( Invoice__c = nextInvId, 
                                                                                Sales_Price__c = invLItem.Sales_Price__c, 
                                                                                Product__c = invLItem.Product__c, 
                                                                                Counts__c = invLItem.Counts__c,
                                                                                CPM__c = invLItem.CPM__c, 
                                                                                Monthly_Frequency__c = invLItem.Monthly_Frequency__c
                                                                               );
                    newInvLItems.add( newInvLItem );
                }
            }
        }
        sYSTEM.debug('---------');
        System.debug(newInvLItems);
        System.debug(invIdNextInvIdMap);
        System.debug(ioIdInvIdsMap);
        System.debug(invIdLItemMap);
        if( newInvLItems.size() > 0 && start == false ){
            start = true;
            INSERT newInvLItems;
        }
    }
    static void fillNextInvIds( List<Id> invIds, Map<Id, List<Id>> invIdNextInvIdMap, Id invId ){
        for( Id invId1 : invIds ){
            if( invId1 > invId ){
                invIdNextInvIdMap.get( invId ).add( invId1 );
            }
        }
    }
}