force-app/main/default/objects/Contract/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>IO</relationshipLabel>
    <relationshipName>IO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>IO Invoice</label>
    <nameField>
        <displayFormat>INV-{000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IO Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/IO__c.field-meta.xml
<CustomField>
    <fullName>IO__c</fullName>
    <label>IO</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>IO Invoices</relationshipLabel>
    <relationshipName>Contract_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Invoice</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>IO Invoice Line Item</label>
    <nameField>
        <displayFormat>INVL-{000}</displayFormat>
        <label>Invoice Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IO Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Ad_Sizes__c.field-meta.xml
<CustomField>
    <fullName>Ad_Sizes__c</fullName>
    <label>Ad Sizes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Counts__c.field-meta.xml
<CustomField>
    <fullName>Counts__c</fullName>
    <label>Counts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/CPM__c.field-meta.xml
<CustomField>
    <fullName>CPM__c</fullName>
    <label>CPM</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/IO__c.field-meta.xml
<CustomField>
    <fullName>IO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IO</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>IO Invoice Line Items</relationshipLabel>
    <relationshipName>IO_Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Monthly_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Frequency__c</fullName>
    <label>Monthly Frequency</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <label>Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Flight_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Flight_End_Date__c</fullName>
    <label>Flight End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Flight_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Flight_Start_Date__c</fullName>
    <label>Flight Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity_Segment__c/Opportunity_Segment__c.object-meta.xml
<CustomObject>
    <label>Opportunity Segment</label>
    <nameField>
        <displayFormat>OS-{000}</displayFormat>
        <label>Opportunity Segment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Segments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Segment__c/fields/IO_Invoice__c.field-meta.xml
<CustomField>
    <fullName>IO_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IO Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Opportunity Segments</relationshipLabel>
    <relationshipName>Opportunity_Segments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Segment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Segments</relationshipLabel>
    <relationshipName>Opportunity_Segments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Segment__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segment</label>
    <referenceTo>Segment__c</referenceTo>
    <relationshipLabel>Opportunity Segments</relationshipLabel>
    <relationshipName>Opportunity_Segments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Monthly_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Frequency__c</fullName>
    <defaultValue>30</defaultValue>
    <label>Monthly Frequency</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_Id__c</fullName>
    <externalId>true</externalId>
    <label>Product Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Segment__c/Segment__c.object-meta.xml
<CustomObject>
    <label>Segment</label>
    <nameField>
        <label>Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OppTriggerHelper.cls
public class OppTriggerHelper {
    public static void createIos( List<Opportunity> opps, Set<Id> oppIds ){
        Map<Id, List<OpportunityLineItem>> oppProdsMap = new Map<Id, List<OpportunityLineItem>>();
        List<Contract> contracts = new List<Contract>();
        List<Invoice_Line_Item__c> invLItems = new List<Invoice_Line_Item__c>();
        List<Invoice__c> invoices = new List<Invoice__c>();
        List<Opportunity_Segment__c> oppSegs = new List<Opportunity_Segment__c>(); 
        boolean first = false;
        for( Opportunity oppProd : [SELECT Id, Pricebook2Id, AccountId, 
                                    Flight_Start_Date__c, Flight_End_Date__c, 
                                    ( SELECT Discount, Ad_Sizes__c, OpportunityId, 
                                     ListPrice, Monthly_Frequency__c, UnitPrice, PricebookEntryId, 
                                     Product2Id, Product2.Name, product2.Product_Id__c, 
                                     Quantity, TotalPrice FROM OpportunityLineItems ),
                                    ( SELECT Segment__c, Opportunity__c, IO_Invoice__c FROM Opportunity_Segments__r ) FROM Opportunity WHERE Id IN :oppIds ] ){
            oppProdsMap.put( oppProd.Id, oppProd.OpportunityLineItems );
            List<OpportunityLineItem> opplItems = oppProd.OpportunityLineItems;
            List<Opportunity_Segment__c> oppSegments = oppProd.Opportunity_Segments__r;
            Date startDate = oppProd.Flight_Start_Date__c;
            Date endDate = oppProd.Flight_End_Date__c;
            Integer contractTerm = startDate.monthsBetween(endDate);
            Contract invoice = new Contract( Pricebook2Id = oppProd.Pricebook2Id, StartDate = startDate, ContractTerm = contractTerm, AccountId = oppProd.AccountId, Opportunity__c = oppProd.Id );
            contracts.add( invoice );
            for( Integer i = 0; i<contractTerm; i++ ){
                Integer numberOfDays = Date.daysInMonth(startDate.year(), startDate.month());
                endDate = startDate.addDays(numberOfDays - startDate.day());
                Invoice__c inv = new Invoice__c( IO__r = invoice, Start_Date__c = startDate, End_Date__c = endDate );		
                invoices.add( inv );
                startDate = endDate.addDays( 1 );
                if( opplItems != null && !first ){
                    for( OpportunityLineItem pItem : opplItems ){
                        Invoice_Line_Item__c invLItem = new Invoice_Line_Item__c();
                        invLItem.Discount__c = pItem.Discount;
                        invLItem.Invoice__r = inv;
                        invLItem.Counts__c = pItem.Quantity;
                        invLItem.Monthly_Frequency__c = pItem.Monthly_Frequency__c;
                        invLItem.CPM__c = pItem.ListPrice;
                        invLItem.Ad_Sizes__c = pItem.Ad_Sizes__c;
                        invLItem.Product__c = pItem.Product2Id;
                        invLItem.Sales_Price__c = pItem.UnitPrice;
                        invLItems.add( invLItem );
                    }   
                    first = true;
                }
                /*if( oppSegments != null ){
                    System.debug('->'+inv);
                    for( Opportunity_Segment__c oppSeg : oppSegments ){
                        System.debug('!!::'+inv);
                        Opportunity_Segment__c oS = new Opportunity_Segment__c( IO_Invoice__r = inv, Segment__c = oppSeg.Segment__c );
                        oppSegs.add( oS );
                    }
                }*/
            }
        }
        if( contracts.size() > 0 ){
            INSERT contracts;
            //Creating Trade desk records
            List<Id> ioIds = new List<Id>();
            for( contract cont : contracts ){
                ioIds.add( cont.id );
            }
            //Database.executeBatch(new CreateTTDAccs( ioIds ), 10);
            if( invoices.size() > 0 ){
                for( Invoice__c invoice : invoices ){
                    invoice.IO__c = invoice.IO__r.Id;
                }
                INSERT invoices;
                if( invLItems.size() > 0 ){
                    for( Invoice_Line_Item__c invLItem : invLItems ){
                        invLItem.Invoice__c = invLItem.Invoice__r.Id;
                    }
                    INSERT invLItems;
                }
                /*System.debug('ONVS:'+invoices);
                if( oppSegs.size() > 0 ){
                    for( Opportunity_Segment__c oppSe : oppSegs ){
                        System.debug('----'+oppSe.IO_Invoice__r);
                        oppSe.IO_Invoice__c = oppSe.IO_Invoice__r.Id;
                    }
                    System.debug(oppSegs);
                    INSERT oppSegs;
                }*/
            }
            
        }
    }
}