force-app/main/default/objects/Contract/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>IO</relationshipLabel>
    <relationshipName>IO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposal</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>IO</relationshipLabel>
    <relationshipName>IO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>IO Invoice</label>
    <nameField>
        <displayFormat>INV-{000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IO Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/IO__c.field-meta.xml
<CustomField>
    <fullName>IO__c</fullName>
    <label>IO</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>IO Invoices</relationshipLabel>
    <relationshipName>Contract_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Invoice</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposal</label>
    <referenceTo>Quote</referenceTo>
    <relationshipName>Invoice</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>IO Invoice Line Item</label>
    <nameField>
        <displayFormat>INVL-{000}</displayFormat>
        <label>Invoice Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IO Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Counts__c.field-meta.xml
<CustomField>
    <fullName>Counts__c</fullName>
    <label>Counts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/CPM__c.field-meta.xml
<CustomField>
    <fullName>CPM__c</fullName>
    <label>CPM</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Impression__c.field-meta.xml
<CustomField>
    <fullName>Impression__c</fullName>
    <formula>( Sales_Price__c  /  CPM__c )*1000</formula>
    <label>Impression</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/IO__c.field-meta.xml
<CustomField>
    <fullName>IO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IO</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>IO Invoice Line Items</relationshipLabel>
    <relationshipName>IO_Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Monthly_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Frequency__c</fullName>
    <label>Monthly Frequency</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <label>Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <errorMessage>Contact should be under the same account</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Brand__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.SubClient_or_Manufacturer__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Impression__c.field-meta.xml
<CustomField>
    <fullName>Impression__c</fullName>
    <formula>( UnitPrice  /  ListPrice ) * 1000</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Impression</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Monthly_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Frequency__c</fullName>
    <defaultValue>30</defaultValue>
    <label>Monthly Frequency</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal_IO_Billing_Contact__c/Proposal_IO_Billing_Contact__c.object-meta.xml
<CustomObject>
    <label>Proposal IO Billing Contact</label>
    <nameField>
        <displayFormat>BC-{000}</displayFormat>
        <label>Proposal Billing Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposal IO Billing Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal_IO_Billing_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Proposal_Billing_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Proposal_IO_Billing_Contact__c/fields/IO__c.field-meta.xml
<CustomField>
    <fullName>IO__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>IO</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>IO Billing Contacts</relationshipLabel>
    <relationshipName>Proposal_IO_Billing_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal_IO_Billing_Contact__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposal</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Proposal Billing Contacts</relationshipLabel>
    <relationshipName>Proposal_Billing_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal_IO_Billing_Contact__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary Contact</fullName>
            </value>
            <value>
                <fullName>Secondary Contact</fullName>
            </value>
            <value>
                <fullName>Billing Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Proposal_IO_Billing_Contact__c/recordTypes/IO.recordType-meta.xml
<RecordType>
    <fullName>IO</fullName>
    <active>true</active>
    <label>IO</label>
</RecordType>

force-app/main/default/classes/ReviseIOCls.cls
public with sharing class ReviseIOCls {
    @AuraEnabled
    public static List<OpportunityLineItem> getProductsOfIO( Id ioId ){
        try {
            Contract io = [SELECT Proposal__r.OpportunityId FROM Contract WHERE Id = :ioId LIMIT 1];
            return [SELECT Product2Id, Product2.Name, UnitPrice, ListPrice, Quantity, Monthly_Frequency__c, Impression__c FROM OpportunityLineItem WHERE OpportunityId = :io.Proposal__r.OpportunityId];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static List<Product2> getProducts( Id ioId ){
        try {
            Contract cont = [ SELECT Proposal__r.Opportunity.Pricebook2Id FROM Contract WHERE Id = :ioId ];
            if( cont.Proposal__r.Opportunity.Pricebook2Id != null ){
                Set<Id> prodIds = new Set<Id>();
                for( PricebookEntry pEntry : [SELECT Id, Name, Product2Id, UnitPrice from PricebookEntry WHERE Pricebook2Id = :cont.Proposal__r.Opportunity.Pricebook2Id] ){
                    prodIds.add( pEntry.Product2Id );
                }
                return [SELECT Name FROM Product2 WHERE Id IN :prodIds];
            }
            return null;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static Id createNewIO( List<OpportunityLineItem> upItems, DateTime startDate1, DateTime endDate1, Id ioId ){
        try {
            Contract c = [SELECT Id, Proposal__r.Opportunity.AccountId, Proposal__r.Opportunity.Pricebook2Id,
                          proposal__r.Opportunity.Primary_Contact__c, Proposal__c, Opportunity__c
                          FROM Contract WHERE Id = :ioId];
            List<Proposal_IO_Billing_Contact__c> ioBillContacts = new List<Proposal_IO_Billing_Contact__c>();
            Set<Id> productIds = new Set<Id>();
            for( OpportunityLineItem pItem : upItems ){
                productIds.add( pItem.Product2Id );
            } 
            Map<Id, Decimal> pIdCPM = new Map<Id, Decimal>();
            for( PricebookEntry pEntry : [SELECT Id, Name, Product2Id, UnitPrice from PricebookEntry WHERE Pricebook2Id = :c.Proposal__r.Opportunity.Pricebook2Id AND Product2Id IN :productIds] ){
                pIdCPM.put( pEntry.Product2Id, pEntry.UnitPrice );
            }
            DateTime dt = startDate1;
            Date startDate = Date.newInstance(dt.year(), dt.month(), dt.day());
            dt = endDate1;
            Date endDate = Date.newInstance(dt.year(), dt.month(), dt.day());
            Integer contractTerm = startDate.monthsBetween(endDate);
            Contract cont = new Contract( Opportunity__c = c.Opportunity__c, AccountId = c.proposal__r.Opportunity.AccountId, StartDate = startDate, ContractTerm = contractTerm, CustomerSignedId = c.proposal__r.Opportunity.Primary_Contact__c, Proposal__c = c.Proposal__c ); 
            ContractTriggerHelper.start = false;
            INSERT cont;
            for( Proposal_IO_Billing_Contact__c billCont : [SELECT Proposal__c, RecordTypeId, Contact__c, IO__c, Role__c FROM Proposal_IO_Billing_Contact__c WHERE IO__c = :ioId] ){
                billCont.IO__c = cont.Id;
                billCont.Id = null;
                ioBillContacts.add( billCont );
            }
            if( ioBillContacts.size() > 0 ){
                INSERT ioBillContacts;
            }
            List<Invoice__c> invoices = new List<Invoice__c>();
            List<Invoice_Line_Item__c> invLItems = new List<Invoice_Line_Item__c>();
            
            for( integer i = 0; i<contractTerm; i++ ){
                Integer numberOfDays = Date.daysInMonth(startDate.year(), startDate.month());
                endDate = startDate.addDays(numberOfDays - startDate.day());
                Invoice__c invoice = new Invoice__c( IO__c = cont.Id, Start_Date__c = startDate, End_Date__c = endDate );   
                startDate = endDate.addDays( 1 );
                
                if( upItems != null ){
                    for( OpportunityLineItem pItem : upItems ){
                        Invoice_Line_Item__c invLItem = new Invoice_Line_Item__c();
                        invLItem.Invoice__r = invoice;
                        invLItem.Product__c = pItem.Product2Id;
                        invLItem.Quantity__c = 1;
                        invLItem.Counts__c = pItem.Quantity;
                        invLItem.Monthly_Frequency__c = pItem.Monthly_Frequency__c;
                        invLItem.CPM__c = pIdCPM.get( pItem.Product2Id ); 
                        invLItem.Sales_Price__c = pItem.UnitPrice;
                        invLItems.add( invLItem );
                    }   
                }
                invoices.add( invoice );
            }
            if( invoices.size() > 0 ){
                INSERT invoices;
                Set<Id> invoiceIds = new Set<Id>();
                for( Invoice__c inv : invoices ){
                    invoiceIds.add( inv.Id );
                }
                if( invLItems.size() > 0 ){
                    for( Invoice_Line_Item__c invLItem : invLItems ){
                        invLItem.Invoice__c = invLItem.Invoice__r.Id;
                    }
                    INSERT invLItems;
                }
                Database.executeBatch(new CreateInvoiceBatchCls(invoiceIds), 10);
            }
            return cont.Id;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}