force-app/main/default/objects/Account/fields/Advertiser_Client__c.field-meta.xml
<CustomField>
    <fullName>Advertiser_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Advertiser Client</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Advertiser Client</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Advertiser Client)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Brand</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Advertiser_Client__c.field-meta.xml
<CustomField>
    <fullName>Advertiser_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Advertiser Client</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Advertiser Client</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Audience_Type__c.field-meta.xml
<CustomField>
    <fullName>Audience_Type__c</fullName>
    <label>Audience Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>HCP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Brand)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Direct__c.field-meta.xml
<CustomField>
    <fullName>Direct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Direct?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loss_Reason__c.field-meta.xml
<CustomField>
    <fullName>Loss_Reason__c</fullName>
    <label>Loss Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Cost too High</fullName>
            </value>
            <value>
                <fullName>Audience too Small</fullName>
            </value>
            <value>
                <fullName>Went to Competitor</fullName>
            </value>
            <value>
                <fullName>Budget on Hold</fullName>
            </value>
            <value>
                <fullName>Unresponsive</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <errorMessage>Contact should be under the same account</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Brand__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.SubClient_or_Manufacturer__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SubClient_or_Manufacturer__c.field-meta.xml
<CustomField>
    <fullName>SubClient_or_Manufacturer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SubClient</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (SubClient or Manufacturer)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Target_Geo_Type__c.field-meta.xml
<CustomField>
    <fullName>Target_Geo_Type__c</fullName>
    <label>Target Geo Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>State</fullName>
            </value>
            <value>
                <fullName>Country</fullName>
            </value>
            <value>
                <fullName>County</fullName>
            </value>
            <value>
                <fullName>Zip</fullName>
            </value>
            <value>
                <fullName>DMA</fullName>
            </value>
            <value>
                <fullName>Radius</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OppRecPageCtrl.cls
public with sharing class OppRecPageCtrl {
    
    @AuraEnabled
    public static Boolean checkAccType( Id accId ){
        try {
            List<Account> acc = [SELECT Id, Type FROM Account WHERE Id = :accId];
            if( acc.size() > 0 ){
                if( acc[0].Type == 'Advertiser Client' ){    
                    return true;
                }
            }
                return false;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static List<String> getOppFields(){
        SObjectType contactType = Schema.getGlobalDescribe().get('Opportunity');
        Map<String,Schema.SObjectField> mfields = contactType.getDescribe().fields.getMap();

        List<String> sObjectDetailsList = new List<String>();
        System.debug( mfields );
        for(String s : mfields.keySet()){
            String fApiName = String.valueOf(mfields.get(s));
            if( fApiName != 'Id' && fApiName != 'IsDeleted' && fApiName != 'RecordTypeId' && fApiName != 'IsPrivate' && fApiName != 'RecordTypeId' && fApiName != 'IsWon' && fApiName != 'IsClosed'
            && fApiName != 'Fiscal' && fApiName != 'FiscalYear'&& fApiName != 'FiscalQuarter'&& fApiName != 'LastStageChangeDate'&& fApiName != 'PushCount'&& fApiName != 'LastActivityDate'&& fApiName != 'SystemModstamp'&& fApiName != 'LastModifiedById'
            && fApiName != 'LastModifiedDate'&& fApiName != 'CreatedById' && fApiName != 'CreatedDate'&& fApiName != 'OwnerId'&& fApiName != 'Pricebook2Id'&& fApiName != 'HasOpportunityLineItem' && fApiName != 'HasOpenActivity' && fApiName != 'SyncedQuoteId'
            && fApiName != 'LastReferencedDate' && fApiName != 'LastViewedDate' && fApiName != 'LastCloseDateChangedHistoryId'&& fApiName != 'LastAmountChangedHistoryId' && fApiName != 'IqScore' && fApiName != 'HasOverdueTask'&& fApiName != 'ForecastCategory'&& fApiName != 'ContactId'
            && fApiName != 'SubClient_or_Manufacturer__c' && fApiName != 'Advertiser_Client__c'&& fApiName != 'Brand__c'
            )
            sObjectDetailsList.add(String.valueOf(mfields.get(s)));
        }
        return sObjectDetailsList;
    }
    // adId = account with type advertiser client
    // AccountToId = account with type subclient
    @AuraEnabled
    public static List<AccountPartner> getAdSubClientsBrands( Id adId ){
        if(adId != null)
        return [SELECT AccountToId, Role, AccountTo.Name FROM AccountPartner WHERE AccountFromId = :adId];
        else {
            return null;
        }
    }
    @AuraEnabled
    public static List<Contact> getContacts( Id adId, Id subId, Id bId ){
        return [SELECT Name, Id FROM Contact WHERE AccountId = :adId OR AccountId = :subId OR AccountId = :bId];
    }
    //Opp record Id
    @AuraEnabled
    public static String getRecTypeName( Id recId ){
        if( recId != null )
            return [SELECT Name, DeveloperName
            FROM RecordType
            WHERE Id = :recId].DeveloperName;
        else    return null;
    }
    @AuraEnabled
    public static Opportunity getEditValue( Id recId ){
        try {   
            if( recId != null ){
                return [ SELECT RecordTypeId, SubClient_or_Manufacturer__c, AccountId, Direct__c,
                        Primary_Contact__c, Brand__c, Audience_Type__c, Target_Geo_Type__c, Loss_Reason__c
                        FROM Opportunity WHERE Id = :recId
                        ];
            }else   return null;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static string saveNewSubClient( Id accId, String subName ){
        try {
            Account acc = new Account( Name = subName, Type='Sub-Client' );
            INSERT acc;
            AccountPartner accP = new AccountPartner( AccountFromId = accId, AccountToId = acc.Id, Role = 'Sub-Client - Advertiser Client' );
            INSERT accP;
            return 'Success';
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

}