force-app/main/default/objects/Account/fields/Board_Link__c.field-meta.xml
<CustomField>
    <fullName>Board_Link__c</fullName>
    <label>Monday Board Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Account/fields/Google_Drive_Link__c.field-meta.xml
<CustomField>
    <fullName>Google_Drive_Link__c</fullName>
    <label>Google Drive Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Account/fields/Google_Drive_Link_Formula__c.field-meta.xml
<CustomField>
    <fullName>Google_Drive_Link_Formula__c</fullName>
    <formula>Google_Drive_Link__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Google Drive Link</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Board_Campaign__c/Board_Campaign__c.object-meta.xml
<CustomObject>
    <label>Board Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Board Campaign</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Board_Campaign__c/fields/Board_Link__c.field-meta.xml
<CustomField>
    <fullName>Board_Link__c</fullName>
    <label>Board Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Board_Campaign__c/fields/OpportunityCamaign__c.field-meta.xml
<CustomField>
    <fullName>OpportunityCamaign__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>campaign</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GoogleDriveCreds__c/GoogleDriveCreds__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Google Drive Creds</label>
</CustomObject>

force-app/main/default/objects/GoogleDriveCreds__c/fields/Access_Token__c.field-meta.xml
<CustomField>
    <fullName>Access_Token__c</fullName>
    <label>Access Token</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/GoogleDriveCreds__c/fields/Client_Secret__c.field-meta.xml
<CustomField>
    <fullName>Client_Secret__c</fullName>
    <label>Client Secret</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Google_Drive_Link__c.field-meta.xml
<CustomField>
    <fullName>Google_Drive_Link__c</fullName>
    <label>Google Drive Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/campaignFolderCreateCls.cls
public class campaignFolderCreateCls {
    
    @InvocableMethod( callout=true )
    public static void createMondayBoard( List<Id> campaignIds ){
        system.debug('campaignIds===>'+campaignIds);
        List<Id> noBoardCampIds = new List<Id>();
        List<Id> boardCampIds = new List<Id>();
        //Database.executeBatch(new CreateGDriveBatch( campaignIds ), 25);
        String sObjName = campaignIds[0].getSObjectType().getDescribe().getName();
        system.debug('sObjeName===>'+sObjName);
        if( sObjName == 'Opportunity' ){
            Database.executeBatch(new CreateGDriveBatch( campaignIds, 'Opportunity' ), 10);
            //Creating Trade desk records
            //Database.executeBatch(new CreateTTDAccs( campaignIds ), 10);
        }/*else if( sObjName == 'Board_Campaign__c' ){
            for(Board_Campaign__c bCampaign : [SELECT Name, OpportunityCamaign__r.Account.Board_Link__c FROM Board_Campaign__c WHERE Id IN :campaignIds]){
                if( bCampaign.OpportunityCamaign__r.Account.Board_Link__c == null ){
                    noBoardCampIds.add( bCampaign.Id );
                }else{
                    boardCampIds.add( bCampaign.Id );
                }
            }
            Database.executeBatch(new CreateBoardBatch( noBoardCampIds, boardCampIds ), 50); 	
        }*/   
    }
    @AuraEnabled
    public static List<Object> getFilesOfFolder( String folderId ){
        GoogleDriveCreds__c gDriveCred = [SELECT Client_Secret__c, Access_Token__c, Client_Id__c FROM GoogleDriveCreds__c LIMIT 1];
        system.debug('gDriveCred--->'+gDriveCred);
        if( gDriveCred != null ){
            String accessToken = gDriveCred.Access_Token__c;
            Http h = new Http();
            HttpRequest req = new HttpRequest();
            System.debug('FolderId:'+folderId);
            //req.setEndPoint('https://www.googleapis.com/drive/v3/files?q=\''+folderId+'\'+in+parents');
            req.setEndPoint('callout:GoogleDrive/drive/v3/files?q=\''+folderId+'\'+in+parents');
            req.setMethod('GET');
            req.setHeader('Content-Type', 'application/json');
            //req.setHeader('Authorization', 'Bearer '+accessToken);
            req.setHeader('Accept', 'application/json');
            HttpResponse res= h.send(req);
            System.debug('FolderFiles:'+res.getBody());
            Map<String, Object> resBody = (Map<String, Object>)JSON.deserializeUntyped( res.getBody() );
            List<Object> files = (List<Object>)resBody.get( 'files' );
            system.debug('files--->'+files);
            return files;
        }
        return null;
    }
    @AuraEnabled
    public static List<Object> getFileNames( Id campaignId, String objName ){
        List<sObject> camp = Database.query('SELECT Name, Google_Drive_Link_Formula__c, Google_Drive_Link__c FROM '+objName+' WHERE Id = :campaignId LIMIT 1');
        system.debug('camp--->'+camp);
        if( camp!=null ){
            if( camp.size() > 0 ){
                String gLink = (String)camp[0].get('Google_Drive_Link_Formula__c');
                String fId = gLink.substring( gLink.lastIndexOf('/')+1 );
                system.debug(fId);
                List<Object> files = getFilesOfFolder(fId);
                return files;        
            }else{
                return null;
            }
        }
        return null;
    }
}