force-app/main/default/objects/Account/fields/Google_Drive_Link__c.field-meta.xml
<CustomField>
    <fullName>Google_Drive_Link__c</fullName>
    <label>Google Drive Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Audience__c/Audience__c.object-meta.xml
<CustomObject>
    <label>Audience</label>
    <nameField>
        <label>Audience Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Audiences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Audience__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segment</label>
    <referenceTo>Segment__c</referenceTo>
    <relationshipLabel>Audiences</relationshipLabel>
    <relationshipName>Audiences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Google_Drive_Link__c.field-meta.xml
<CustomField>
    <fullName>Google_Drive_Link__c</fullName>
    <label>Google Drive Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>IO</relationshipLabel>
    <relationshipName>IO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>IO Invoice</label>
    <nameField>
        <displayFormat>INV-{000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IO Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/IO__c.field-meta.xml
<CustomField>
    <fullName>IO__c</fullName>
    <label>IO</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>IO Invoices</relationshipLabel>
    <relationshipName>Contract_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Invoice</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>IO Invoice Line Item</label>
    <nameField>
        <displayFormat>INVL-{000}</displayFormat>
        <label>Invoice Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IO Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/IO__c.field-meta.xml
<CustomField>
    <fullName>IO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IO</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>IO Invoice Line Items</relationshipLabel>
    <relationshipName>IO_Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <label>Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Audience_Type__c.field-meta.xml
<CustomField>
    <fullName>Audience_Type__c</fullName>
    <label>Audience Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>HCP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Direct__c.field-meta.xml
<CustomField>
    <fullName>Direct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Direct?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Flight_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Flight_End_Date__c</fullName>
    <label>Flight End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Flight_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Flight_Start_Date__c</fullName>
    <label>Flight Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Google_Drive_Link__c.field-meta.xml
<CustomField>
    <fullName>Google_Drive_Link__c</fullName>
    <label>Google Drive Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Opportunity_Segment__c/Opportunity_Segment__c.object-meta.xml
<CustomObject>
    <label>Opportunity Segment</label>
    <nameField>
        <displayFormat>OS-{000}</displayFormat>
        <label>Opportunity Segment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Segments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Segment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Segments</relationshipLabel>
    <relationshipName>Opportunity_Segments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Segment__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segment</label>
    <referenceTo>Segment__c</referenceTo>
    <relationshipLabel>Opportunity Segments</relationshipLabel>
    <relationshipName>Opportunity_Segments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Segment__c/Segment__c.object-meta.xml
<CustomObject>
    <label>Segment</label>
    <nameField>
        <label>Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OppSegTriggerHelperTest.cls
@isTest
public class OppSegTriggerHelperTest {
    
    @isTest
    public static void createAudienceInIterable(){
        Account acc = new Account(name='acc1');
        insert acc;
        Contract con  = new Contract(name='contract1',AccountID = acc.id,status= 'Draft');
        insert con;
        Invoice__c Inv = new Invoice__c(IO__c = con.id,Start_Date__c = date.today(), End_Date__c = date.today().addMonths(1));
        insert Inv;
        Product2 product = new Product2(Name='EmailExample', isActive=true);
        Test.startTest();
        // OppSegTriggerHelper.createAudienceInIterable();
        Test.setMock(HttpCalloutMock.class, new OppSegTriggerHelperMockCallout());
        insert product;
        Invoice_Line_Item__c  InvoiceLine = new Invoice_Line_Item__c(Invoice__c = Inv.Id,Product__c=product.id, Sales_Price__c=9000.00);
        insert InvoiceLine;
        Date endDate = date.today().addMonths(2);
        Segment__c seg = new Segment__c(Name = 'Segment1');
        insert seg;
        Audience__c Audi =  new Audience__c(First_Name__c='Audi1',Segment__c = seg.id);
        insert Audi;
        Opportunity opp = new opportunity(Name= 'opp',CloseDate=date.today(), AccountId = acc.id, StageName='Needs Analysis', Audience_Type__C = 'HCP', Flight_Start_Date__c = date.today(), Flight_End_Date__c = endDate ,Direct__c=false,Google_Drive_Link__c='https://drive.google.com/drive/u/0/folders/1_3Z-hZ4H8onW0I4ccrmE5Z9j-kp1xxT9');
        insert opp;
        Opportunity_Segment__c OppSegment = new Opportunity_Segment__c(Opportunity__c = opp.id,Segment__c = seg.id,IO_Invoice_Line_Item__c=InvoiceLine.id);
        insert OppSegment;
        Test.stopTest();
    }
    
    @isTest
    public static void updateOppAudUPDATETest(){
        Account acc = new Account(name='acc1');
        insert acc;
        Contract con  = new Contract(name='contract1',AccountID = acc.id,status= 'Draft');
        insert con;
        Invoice__c Inv = new Invoice__c(IO__c = con.id,Start_Date__c = date.today(), End_Date__c = date.today().addMonths(1));
        insert Inv;
        Product2 product = new Product2(Name='EmailExample', isActive=true);
        Test.startTest();
        // OppSegTriggerHelper.createAudienceInIterable();
        Test.setMock(HttpCalloutMock.class, new OppSegTriggerHelperMockCallout());
        insert product;
        Invoice_Line_Item__c  InvoiceLine = new Invoice_Line_Item__c(Invoice__c = Inv.Id,Product__c=product.id, Sales_Price__c=9000.00);
        insert InvoiceLine;
        Date endDate = date.today().addMonths(2);
        Segment__c seg = new Segment__c(Name = 'Segment1');
        insert seg;
        Audience__c Audi =  new Audience__c(First_Name__c='Audi1',Segment__c = seg.id);
        insert Audi;
        Opportunity opp = new opportunity(Name= 'opp',CloseDate=date.today(), AccountId = acc.id, StageName='Needs Analysis', Audience_Type__C = 'HCP', Flight_Start_Date__c = date.today(), Flight_End_Date__c = endDate ,Direct__c=false,Google_Drive_Link__c='https://drive.google.com/drive/u/0/folders/1_3Z-hZ4H8onW0I4ccrmE5Z9j-kp1xxT9');
        insert opp;
        Opportunity_Segment__c OppSegment = new Opportunity_Segment__c(Opportunity__c = opp.id,Segment__c = seg.id,IO_Invoice_Line_Item__c=InvoiceLine.id);
        insert OppSegment;
        
        update OppSegment;
        Test.stopTest();
    }
    
    @isTest
    public static void updateOppAudDELETETest(){
        Account acc = new Account(name='acc1');
        insert acc;
        Contract con  = new Contract(name='contract1',AccountID = acc.id,status= 'Draft');
        insert con;
        Invoice__c Inv = new Invoice__c(IO__c = con.id,Start_Date__c = date.today(), End_Date__c = date.today().addMonths(1));
        insert Inv;
        Product2 product = new Product2(Name='EmailExample', isActive=true);
        Test.startTest();
        // OppSegTriggerHelper.createAudienceInIterable();
        Test.setMock(HttpCalloutMock.class, new OppSegTriggerHelperMockCallout());
        insert product;
        Invoice_Line_Item__c  InvoiceLine = new Invoice_Line_Item__c(Invoice__c = Inv.Id,Product__c=product.id, Sales_Price__c=9000.00);
        insert InvoiceLine;
        Date endDate = date.today().addMonths(2);
        Segment__c seg = new Segment__c(Name = 'Segment1');
        insert seg;
        Audience__c Audi =  new Audience__c(First_Name__c='Audi1',Segment__c = seg.id);
        insert Audi;
        Opportunity opp = new opportunity(Name= 'opp',CloseDate=date.today(), AccountId = acc.id, StageName='Needs Analysis', Audience_Type__C = 'HCP', Flight_Start_Date__c = date.today(), Flight_End_Date__c = endDate ,Direct__c=false,Google_Drive_Link__c='https://drive.google.com/drive/u/0/folders/1_3Z-hZ4H8onW0I4ccrmE5Z9j-kp1xxT9');
        insert opp;
        Opportunity_Segment__c OppSegment = new Opportunity_Segment__c(Opportunity__c = opp.id,Segment__c = seg.id,IO_Invoice_Line_Item__c=InvoiceLine.id);
        insert OppSegment;
        Delete OppSegment;
        Test.stopTest();
    }
    
      @testSetup static void setup() {
        /*Account acc = new Account(name='acc1');
        insert acc;
        Contract con  = new Contract(name='contract1',AccountID = acc.id,status= 'Draft');
        insert con;
        Invoice__c Inv = new Invoice__c(IO__c = con.id,Start_Date__c = date.today(), End_Date__c = date.today().addMonths(1));
        insert Inv;
        Product2 product = new Product2(Name='EmailExample', isActive=true);
          
        insert product;
        Invoice_Line_Item__c  InvoiceLine = new Invoice_Line_Item__c(Invoice__c = Inv.Id,Product__c=product.id, Sales_Price__c=9000.00);
        insert InvoiceLine;
        Date endDate = date.today().addMonths(2);
        Segment__c seg = new Segment__c(Name = 'Segment1');
        insert seg;
        Audience__c Audi =  new Audience__c(First_Name__c='Audi1',Segment__c = seg.id);
        insert Audi;
        Opportunity opp = new opportunity(Name= 'opp',CloseDate=date.today(), AccountId = acc.id, StageName='Needs Analysis', Audience_Type__C = 'HCP', Flight_Start_Date__c = date.today(), Flight_End_Date__c = endDate ,Direct__c=false,Google_Drive_Link__c='https://drive.google.com/drive/u/0/folders/1_3Z-hZ4H8onW0I4ccrmE5Z9j-kp1xxT9');
        insert opp;
        Opportunity_Segment__c OppSegment = new Opportunity_Segment__c(Opportunity__c = opp.id,Segment__c = seg.id,IO_Invoice_Line_Item__c=InvoiceLine.id);
        insert OppSegment;*/
}
}