force-app/main/default/objects/Contact/fields/QB_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>QB_Customer_Id__c</fullName>
    <label>QB Customer Id</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>IO</relationshipLabel>
    <relationshipName>IO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposal</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>IO</relationshipLabel>
    <relationshipName>IO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>IO Invoice</label>
    <nameField>
        <displayFormat>INV-{000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IO Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/IO__c.field-meta.xml
<CustomField>
    <fullName>IO__c</fullName>
    <label>IO</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>IO Invoices</relationshipLabel>
    <relationshipName>Contract_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposal</label>
    <referenceTo>Quote</referenceTo>
    <relationshipName>Invoice</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <label>Total Price</label>
    <summarizedField>Invoice_Line_Item__c.Sales_Price__c</summarizedField>
    <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>IO Invoice Line Item</label>
    <nameField>
        <displayFormat>INVL-{000}</displayFormat>
        <label>Invoice Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IO Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/IO__c.field-meta.xml
<CustomField>
    <fullName>IO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IO</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>IO Invoice Line Items</relationshipLabel>
    <relationshipName>IO_Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <label>Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <formula>Quantity__c*Sales_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <errorMessage>Contact should be under the same account</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Brand__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.SubClient_or_Manufacturer__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_Id__c</fullName>
    <externalId>true</externalId>
    <label>Product Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quickbook_Creds__mdt/Quickbook_Creds__mdt.object-meta.xml
<CustomObject>
    <label>Quickbook Creds</label>
    <pluralLabel>Quickbook Creds</pluralLabel>
</CustomObject>

force-app/main/default/objects/Quickbook_Creds__mdt/fields/Access_Token__c.field-meta.xml
<CustomField>
    <fullName>Access_Token__c</fullName>
    <label>Access Token</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quickbook_Creds__mdt/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quickbook_Creds__mdt/fields/realmId__c.field-meta.xml
<CustomField>
    <fullName>realmId__c</fullName>
    <label>realmId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quickbook_Creds__mdt/fields/Redirect_uri__c.field-meta.xml
<CustomField>
    <fullName>Redirect_uri__c</fullName>
    <label>Redirect uri</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <label>Total Price</label>
    <summarizedField>Proposal_Invoice__c.Total_Price__c</summarizedField>
    <summaryForeignKey>Proposal_Invoice__c.Proposal__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/CreateInvoiceBatchCls.cls
public class CreateInvoiceBatchCls implements Database.Batchable<sObject>, Database.AllowsCallouts {
    Set<Id> ioInvoiceIds = new Set<Id>();
    public CreateInvoiceBatchCls( Set<Id> qIds ){
        ioInvoiceIds = qIds;
    }
    public Database.QueryLocator start( Database.BatchableContext bc ){
        return Database.getQueryLocator([SELECT Start_Date__c, End_Date__c, IO__r.Proposal__r.Opportunity.Primary_contact__c FROM Invoice__c WHERE Id IN :ioInvoiceIds]);
    }
    public void execute( Database.BatchableContext bc, List<Invoice__c> ioInvoices ){
        Map<Id, Contact> cIdContactMap = new Map<Id, Contact>();
        Map<Id, Contact> invoiceContactMap = new Map<Id, Contact>();
        Set<Id> contactIds = new Set<Id>();
        for( Invoice__c inv : ioInvoices ){
            contactIds.add( inv.IO__r.Proposal__r.Opportunity.Primary_contact__c );
        }
        for( Contact cont : [SELECT Id, QB_Customer_Id__c, Email, Name FROM Contact WHERE Id IN :contactIds] ){
            cIdContactMap.put( cont.id, cont );
        }
        for( Invoice__c inv : ioInvoices ){
            if( cIdContactMap.containsKey(inv.IO__r.Proposal__r.Opportunity.Primary_contact__c) ){
                if( !invoiceContactMap.containsKey(inv.Id) ){
                	invoiceContactMap.put( inv.Id, new Contact() );    
                }
                invoiceContactMap.put( inv.Id, cIdContactMap.get(inv.IO__r.Proposal__r.Opportunity.Primary_contact__c) );    
            }
        }
        List<Invoice_Line_Item__c> quoteLItems = [SELECT Discount__c, Invoice__c, Sales_Price__c, Product__c, Product__r.Name, product__r.Product_Id__c, Quantity__c, Total_Price__c FROM Invoice_Line_Item__c WHERE Invoice__c IN :ioInvoiceIds];
        Quickbook_Creds__mdt cred = [SELECT Id, realmId__c, Client_Secret__c, MasterLabel, DeveloperName, Refresh_Token__c, redirect_uri__c, Client_Id__c, Access_Token__c, Endpoint__c FROM Quickbook_Creds__mdt WHERE DeveloperName = 'Creds'];
        Map<Id, List<Invoice_Line_Item__c>> quoteIdLItemMap = new Map<Id, List<Invoice_Line_Item__c>>();
        for( Invoice_Line_Item__c qLItem : quoteLItems ){
            if( !quoteIdLItemMap.containsKey(qLItem.Invoice__c) ){
                quoteIdLItemMap.put( qLItem.Invoice__c, new List<Invoice_Line_Item__c>() );
            }
            quoteIdLItemMap.get(qLItem.Invoice__c).add( qLItem );
        }
        List<Contact> contacts = new List<Contact>();
        for( Invoice__c quot : ioInvoices ){
            if( invoiceContactMap.containsKey(quot.Id) ){
                Contact cont = invoiceContactMap.get( quot.Id );
                String cusId = cont.QB_Customer_Id__c;
                if( cont.QB_Customer_Id__c == null ){
                    Http h = new Http();
                    String endpoint = cred.Endpoint__c+'/'+cred.realmId__c+'/customer?minorversion=65';
                    HttpRequest req = new HttpRequest();
                    req.setEndPoint(endpoint);
                    req.setHeader('Authorization', 'Bearer '+cred.Access_Token__c);
                    req.setHeader( 'Content-Type', 'application/json' );
                    req.setHeader('Accept', 'application/json');
                    req.setMethod('POST');
                    req.setBody('{ "PrimaryEmailAddr": {"Address": "'+cont.Email+'"}, "DisplayName": "'+cont.Name+'"}');
                    HttpResponse res= h.send(req);
                    Map<String, Object> resBody = (Map<String, Object>)JSON.deserializeUntyped(res.getBody());
                    System.debug(resBody);
                    Map<String,Object> cusMap = (Map<String,Object>)resBody.get('Customer');
                    cont.QB_Customer_Id__c = (String)cusMap.get('Id');
                    cusId = cont.QB_Customer_Id__c;
                    contacts.add( cont );
                }
                if( cusId != null ){
                    createQBInvoice( quot.Id, cusId, quoteIdLItemMap.get( quot.Id ), quot.Start_Date__c, quot.End_Date__c );
                }    
            }
        }
        if( contacts.size() > 0 ){
            UPDATE contacts;    
        }
    }
    public static void createQBInvoice( Id quoteId, String cId, List<Invoice_Line_Item__c> quoteLItems, Date sDate, Date eDate ){
        Quickbook_Creds__mdt cred = [SELECT Id, realmId__c, Client_Secret__c, MasterLabel, DeveloperName, Refresh_Token__c, redirect_uri__c, Client_Id__c, Access_Token__c, Endpoint__c FROM Quickbook_Creds__mdt WHERE DeveloperName = 'Creds'];
        Http h = new Http();
        String endpoint = cred.Endpoint__c+'/'+cred.realmId__c+'/invoice?minorversion=65';
        HttpRequest req = new HttpRequest();
        req.setEndPoint(endpoint);
        req.setHeader('Authorization', 'Bearer '+cred.Access_Token__c);
        req.setHeader( 'Content-Type', 'application/json' );
        req.setHeader('Accept', 'application/json');
        req.setMethod('POST');
        String body = '{"Line": [';
        if( quoteLItems != null ){
            if( quoteLItems.size() > 0 ){
                for( Invoice_Line_Item__c oppLItem : quoteLItems ){
                    body+='{"DetailType": "SalesItemLineDetail", "SalesItemLineDetail": { "Qty": '+oppLItem.Quantity__c+', "UnitPrice": '+oppLItem.Sales_Price__c+', "ItemRef": {"name": "'+oppLItem.Product__r.Name+'", "value": "'+oppLItem.product__r.Product_Id__c+'"}}, "Amount": '+oppLItem.Total_Price__c+'},';
                }
                body = body.substring(0, body.length()-1);    
            }
        }
        body+='],"CustomerRef": {"value": "'+cId+'"},"DueDate" : "'+eDate+'","TxnDate":"'+sDate+'"}';
        System.debug('Body:'+body);
        req.setBody(body);
        HttpResponse res= h.send(req);
        Map<String, Object> resBody = (Map<String, Object>)JSON.deserializeUntyped(res.getBody());
        System.debug(resBody);
    }
    public void finish( Database.BatchableContext bc ){
        
    }
}