force-app/main/default/objects/Proposal_Invoice__c/Proposal_Invoice__c.object-meta.xml
<CustomObject>
    <label>Proposal Invoice</label>
    <nameField>
        <displayFormat>PIN-{000}</displayFormat>
        <label>Proposal Inovice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposal Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteLineItem/fields/Proposal_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposal Invoice</label>
    <referenceTo>Proposal_Invoice__c</referenceTo>
    <relationshipLabel>Proposal Line Items</relationshipLabel>
    <relationshipName>Proposal_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProposalLineItemTriggerHelper.cls
public class ProposalLineItemTriggerHelper {
    public static void addTotalPrice( List<QuoteLineItem> lItems ){
        Set<Id> pInvoiceIds = new Set<Id>();
        for( QuoteLineItem qLItem : lItems ){
            pInvoiceIds.add( qLItem.Proposal_Invoice__c );
        }
        List<Proposal_Invoice__c> pInvoices = [ SELECT Total_Price__c, (SELECT TotalPrice FROM Proposal_Line_Items__r) FROM Proposal_Invoice__c WHERE Id IN :pInvoiceIds ];
        for( Proposal_Invoice__c pInvoice : pInvoices ){
            if( pInvoice.Proposal_Line_Items__r.size() > 0 ){
                Decimal tPrice = 0;
                for( QuoteLineItem pLItem : pInvoice.Proposal_Line_Items__r ){
                    tPrice += pLItem.TotalPrice;
                }
                pInvoice.Total_Price__c = tPrice;
            }
        }
        if( pInvoices.size() > 0 ){
            UPDATE pInvoices;
        }
    }
}